# Generated by Django 4.2.4 on 2023-09-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_tag_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
