# Generated by Django 4.2.4 on 2023-09-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.CharField(max_length=100),
        ),
    ]
