# Generated by Django 4.2.4 on 2023-09-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contry',
            new_name='country',
        ),
    ]
